# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='paragraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=20)),
                ('Last_name', models.CharField(max_length=20)),
                ('Add_line1', models.TextField()),
                ('Add_line2', models.TextField()),
                ('City', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=20)),
                ('Zip', models.IntegerField()),
                ('Email', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=30)),
            ],
        ),
    ]
