# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 23:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0002_auto_20170426_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paragraph',
            old_name='phone',
            new_name='Phone',
        ),
    ]
