# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0003_auto_20170426_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='Phone',
            field=models.CharField(max_length=30),
        ),
    ]
